image: python:3.10.6

default:
  tags:
    - dit

stages:
  - lint
  - run

code lint:
  stage: lint
  script:
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install -U pip wheel
    - pip install poetry
    - poetry install --no-interaction
    - make check
  except:
    - api
    - web

tests:
  stage: run
  script:
    - make test
  only:
    - api
    - web
